# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Helm chart
  run_once: true
  kubernetes.core.helm:
    name: "{{ goldpinger_helm_release_name }}"
    chart_ref: "{{ goldpinger_helm_chart_ref }}"
    release_namespace: "{{ goldpinger_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: "{{ goldpinger_helm_kubeconfig }}"
    values: "{{ _goldpinger_helm_values | combine(goldpinger_helm_values, recursive=True) }}"

- name: Ensure Argo CD is installed and list apps
  ansible.builtin.include_role:
    name: common
    tasks_from: argocd_check

- name: Onboard current service to Argo CD if needed
  ansible.builtin.include_tasks: argocd_onboard.yml
