galaxy_info:
  author: Your Name or Org
  description: Ansible role to install MetalLB via Helm
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: Ubuntu
      versions: [focal, jammy]

dependencies:
  - role: defaults
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      upload_helm_chart_src: "{{ metallb_helm_chart_path }}"
      upload_helm_chart_dest: "{{ metallb_helm_chart_ref }}"
