annotations:
  artifacthub.io/category: security
  artifacthub.io/changes: |2
        - kind: added
          description: "Add support for simultaneous HTTP and HTTPS ports via new httpsEnabled flag"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Keycloak
      url: https://www.keycloak.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak
    - name: Application
      url: https://github.com/keycloak/keycloak
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  license: Apache-2.0
apiVersion: v2
appVersion: 26.5.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.x.x
- condition: postgres.enabled
  name: postgres
  repository: oci://registry-1.docker.io/cloudpirates
  version: 0.9.x
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/cloudpirates
  version: 0.4.x
description: Open Source Identity and Access Management Solution
home: https://www.keycloak.org
icon: https://a.storyblok.com/f/143071/512x512/6a85e594b2/keycloak-logo.svg
keywords:
- keycloak
- identity
- access-management
- authentication
- authorization
- oauth
- openid-connect
- saml
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: keycloak
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak
- https://github.com/keycloak/keycloak
type: application
version: 0.13.0
