# SPDX-License-Identifier: Apache-2.0

# Cloudflare API token to be used by cert-manager solvers
cert_manager_cloudflare_api_token: "8ft-e1xSs9aUxGwgXTbkQPVp9q7WSM_0OlzWVBXt"

# Email address for Let's Encrypt
cert_manager_email: "kaiwueke@gmail.com"

# DNS zones handled by this cert-manager setup
cert_manager_dns_zones:
  - daalu.io

cert_manager_certificates:
  - name: daalu-io
    namespace: istio-ingress
    secret_name: daalu-io-tls
    dns_names:
      - daalu.io
      - '*.daalu.io'
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-prod
