configure:
  languages:
    go: true
    python: true
  plugins:
    - .aspect/cli/shell.star
    - .aspect/cli/pytest_main.star
    - .aspect/cli/go_image.star
    - .aspect/cli/py3_image.star

plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0
