# Where to install Argo CD
argocd_namespace: argocd

# Kubeconfig on the control machine
argocd_local_kubeconfig: "{{ lookup('env','KUBECONFIG') | default('/etc/kubernetes/admin.conf', true) }}"

#argocd_local_kubeconfig: /etc/kubernetes/admin.conf

# Path (on the control machine) to your deployKF overlay dir containing kustomization.yaml
# Example: .../deployKF/argocd-plugin/argocd-install
# argocd CLI install options
argocd_cli_version: "v2.12.6"
argocd_cli_path: "/usr/local/bin/argocd"
argocd_cli_download_url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_cli_version }}/argocd-linux-amd64"

# Use --insecure on argocd login (set false if you have a valid TLS cert)
argocd_login_insecure: true

# Optional: Git repo to add to Argo CD (via CLI)
argocd_repo_url: "git@github.com:kiwueke1/argocd-infrastructure-app.git"
argocd_repo_ssh_private_key_path: "~/.ssh/openstack-key"
argocd_kustomize_dir: "{{ role_path }}/../../../charts/argocd/kustomize"
