---
- name: Configure inotify limits in sysctl.conf
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  with_items:
    - key: fs.inotify.max_user_instances
      value: "1280"
    - key: fs.inotify.max_user_watches
      value: "655360"
