{{- if .Values.clusterOperator.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "cloudpirates.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- $podLabels := include "cloudpirates.tplvalues.merge" ( dict "values" ( list .Values.clusterOperator.podLabels .Values.commonLabels ) "context" . ) }}
  podSelector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq-operator
      app.kubernetes.io/part-of: rabbitmq
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.clusterOperator.networkPolicy.allowExternalEgress }}
  egress:
    - {}
  {{- else }}
  egress:
    - ports:
        # Allow dns resolution
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        # Allow access to kube-apiserver
        {{- range $port := .Values.clusterOperator.networkPolicy.kubeAPIServerPorts }}
        - port: {{ $port }}
        {{- end }}
    # RabbitMQCluster instances have the label app.kubernetes.io/component: rabbitmq
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: rabbitmq
        {{- if not .Values.clusterOperator.watchAllNamespaces }}
        {{- $watchNamespaces := default (list (include "cloudpirates.namespace" .)) .Values.clusterOperator.watchNamespaces }}
          namespaceSelector:
            matchExpressions:
              - key: namespace
                operator: In
                values:
                {{- range $namespace := $watchNamespaces }}
                  - {{ $namespace }}
                {{- end }}
        {{- end }}
    {{- if .Values.clusterOperator.networkPolicy.extraEgress }}
    {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  ingress:
    {{- if .Values.clusterOperator.metrics.service.enabled }}
    - ports:
        - port: {{ .Values.clusterOperator.containerPorts.metrics }}
      {{- if not .Values.clusterOperator.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{- include "rmqco.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/part-of: rabbitmq
        - podSelector:
            matchLabels:
              {{ template "cloudpirates.fullname" . }}-client: "true"
        {{- if .Values.clusterOperator.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.clusterOperator.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.clusterOperator.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.clusterOperator.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.clusterOperator.networkPolicy.extraIngress }}
    {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.networkPolicy.extraIngress "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
