{{- if .Values.clusterOperator.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
    {{- if .Values.clusterOperator.metrics.podMonitor.additionalLabels }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" .Values.clusterOperator.metrics.podMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-metrics" (include "rmqco.clusterOperator.fullname" .) }}
  namespace: {{ default (include "cloudpirates.namespace" .) .Values.msgTopologyOperator.metrics.podMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.clusterOperator.metrics.podMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      {{- if .Values.clusterOperator.metrics.podMonitor.selector }}
      {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.podMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: rabbitmq-operator
  namespaceSelector:
    matchNames:
      - {{ include "cloudpirates.namespace" . }}
  podMetricsEndpoints:
    - port: http
      {{- if .Values.clusterOperator.metrics.podMonitor.interval }}
      interval: {{ .Values.clusterOperator.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.honorLabels }}
      honorLabels: {{ .Values.clusterOperator.metrics.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.clusterOperator.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.relabelings }}
      relabelings: {{ toYaml .Values.clusterOperator.metrics.podMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.clusterOperator.metrics.podMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
    - port: metrics
      {{- if .Values.clusterOperator.metrics.podMonitor.path }}
      path: {{ .Values.clusterOperator.metrics.podMonitor.path }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.params }}
      params: {{ toYaml .Values.clusterOperator.metrics.podMonitor.params | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.interval }}
      interval: {{ .Values.clusterOperator.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.clusterOperator.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.honorLabels }}
      honorLabels: {{ .Values.clusterOperator.metrics.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.relabelings }}
      relabelings: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.podMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.podMonitor.metricRelabelings }}
      metricRelabelings: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.podMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
