{{- if and .Values.clusterOperator.metrics.serviceMonitor.enabled .Values.clusterOperator.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "rmqco.clusterOperator.fullname" . }}
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
    {{- if .Values.clusterOperator.metrics.serviceMonitor.additionalLabels }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" .Values.clusterOperator.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  namespace: {{ default (include "cloudpirates.namespace" .) .Values.clusterOperator.metrics.serviceMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.clusterOperator.metrics.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq-operator
      {{- if .Values.clusterOperator.metrics.serviceMonitor.selector }}
      {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.serviceMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "cloudpirates.namespace" . }}
  endpoints:
    - port: http
      {{- if .Values.clusterOperator.metrics.serviceMonitor.path }}
      path: {{ .Values.clusterOperator.metrics.serviceMonitor.path }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.params }}
      params: {{ toYaml .Values.clusterOperator.metrics.serviceMonitor.params | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.interval }}
      interval: {{ .Values.clusterOperator.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.clusterOperator.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.clusterOperator.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clusterOperator.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.clusterOperator.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
