- name: Check if OpenSearch is already added to Argo CD
  ansible.builtin.debug:
    msg: "OpenSearch already onboarded to Argo CD"
  when: "'opensearch' in argocd_apps_list | map('lower') | list"
  delegate_to: localhost
  run_once: true

- name: Download and apply OpenSearch Argo CD app if not already present
  block:
    - name: Wait for Argo CD CRDs to be available
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: applications.argoproj.io
        kubeconfig: "~/.kube/config"
      register: argocd_crd
      until: argocd_crd.resources is defined and (argocd_crd.resources | length > 0)
      retries: 30
      delay: 10
      delegate_to: localhost
      run_once: true
    - name: Download Argo CD app manifest via GitHub v3 API
      ansible.builtin.uri:
        url: "https://api.github.com/repos/kiwueke1/argocd-infrastructure-app/contents/apps/opensearch/opensearch.yaml"
        method: GET
        return_content: true
        headers:
          Accept: "application/vnd.github.v3.raw"
          Authorization: "token {{ github_token }}"
      register: opensearch_raw_yaml
      delegate_to: localhost
      run_once: true

    - name: Write Argo CD app manifest to file
      ansible.builtin.copy:
        dest: /tmp/opensearch-argocd-app.yaml
        content: "{{ opensearch_raw_yaml.content }}"
      delegate_to: localhost
      run_once: true

    - name: Apply OpenSearch Argo CD app
      kubernetes.core.k8s:
        state: present
        src: /tmp/opensearch-argocd-app.yaml
        kubeconfig: "~/.kube/config"
      register: apply_opensearch_argocd
      delegate_to: localhost
      run_once: true

  when: "'opensearch' not in argocd_apps_list | map('lower') | list"
