annotations:
  artifacthub.io/changes: |2
        - kind: changed
          description: "rename templates from common.* to cloudpirates.* to prevent collisions (#377)"
          links:
            - name: "Commit 07c6560"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/07c6560"
  license: Apache-2.0
apiVersion: v2
appVersion: 2.1.0
description: A library chart for common templates and helper functions
home: https://www.cloudpirates.io
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
name: common
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/common
type: library
version: 2.1.0
