{{- if and .Values.msgTopologyOperator.enabled .Values.msgTopologyOperator.rbac.create }}
{{- if .Values.msgTopologyOperator.watchAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
  name: {{ template "rmqco.msgTopologyOperator.fullname.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "rmqco.msgTopologyOperator.fullname.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rmqco.msgTopologyOperator.serviceAccountName" . }}
    namespace: {{ include "cloudpirates.namespace" . }}
{{- else }}
{{- $watchNamespaces := default (list (include "cloudpirates.namespace" .)) .Values.msgTopologyOperator.watchNamespaces }}
{{- range $namespace := $watchNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-%s" (include "rmqco.msgTopologyOperator.fullname" $) $namespace | trunc 63 | trimSuffix "-" }}
  namespace: {{ $namespace | quote }}
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "rmqco.msgTopologyOperator.fullname.namespace" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rmqco.msgTopologyOperator.serviceAccountName" $ }}
    namespace: {{ include "cloudpirates.namespace" $ | quote }}
{{- end }}
{{- end }}
{{- end }}
