{{- if and .Values.msgTopologyOperator.enabled  .Values.msgTopologyOperator.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "rmqco.msgTopologyOperator.fullname" . }}
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
    {{- if .Values.msgTopologyOperator.metrics.podMonitor.additionalLabels }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" .Values.msgTopologyOperator.metrics.podMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  namespace: {{ default (include "cloudpirates.namespace" .) .Values.msgTopologyOperator.metrics.podMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.msgTopologyOperator.metrics.podMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.selector }}
      {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.msgTopologyOperator.metrics.podMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: messaging-topology-operator
  namespaceSelector:
    matchNames:
      - {{ include "cloudpirates.namespace" . }}
  podMetricsEndpoints:
    - port: http-metrics
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.interval }}
      interval: {{ .Values.msgTopologyOperator.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.honorLabels }}
      honorLabels: {{ .Values.msgTopologyOperator.metrics.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.msgTopologyOperator.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.relabelings }}
      relabelings: {{ toYaml .Values.msgTopologyOperator.metrics.podMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.podMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.msgTopologyOperator.metrics.podMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
{{- end }}
