{{- if and .Values.msgTopologyOperator.enabled .Values.msgTopologyOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
  name: {{ template "rmqco.msgTopologyOperator.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "rmqco.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "rmqco.msgTopologyOperator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rmqco.msgTopologyOperator.serviceAccountName" . }}
    namespace: {{ include "cloudpirates.namespace" . }}
{{- end }}
