- name: Ensure passlib is installed on nodes
  ansible.builtin.pip:
    name: passlib
    state: present
    
- name: Create user 'kez'
  user:
    name: kez
    password: "{{ 'admin10' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Create .ssh directory for kez
  file:
    path: /home/kez/.ssh
    state: directory
    owner: kez
    group: kez
    mode: '0700'

- name: Add SSH public key for kez
  copy:
    dest: /home/kez/.ssh/authorized_keys
    content: "{{ lookup('file', '~/.ssh/openstack-key.pub') }}"
    owner: kez
    group: kez
    mode: '0600'

- name: Allow 'kez' passwordless sudo
  copy:
    dest: /etc/sudoers.d/kez
    content: "kez ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Get ens18 IP address
  ansible.builtin.shell: ip addr show ens18 | grep -w inet | awk '{print $2}' | cut -d'/' -f1
  register: ens18_ip
  changed_when: false

- name: Add host entry with ens18 IP
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ens18_ip.stdout }} {{ inventory_hostname }}.kez-ironcloud.duckdns.org {{ inventory_hostname }}"
    regexp: "^{{ ens18_ip.stdout }}.*$"
    state: present
