images:
  tags:
    placement: docker.io/openstackhelm/placement:2024.1-ubuntu_jammy
    placement_db_sync: docker.io/openstackhelm/placement:2024.1-ubuntu_jammy
    db_init: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    db_drop: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    ks_user: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    ks_service: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    ks_endpoints: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
pod:
  replicas:
    api: 1
conf:
  placement:
    DEFAULT:
      log_config_append: null
    database:
      connection_recycle_time: 600
      max_overflow: 50
      max_pool_size: 5
      max_retries: -1
      pool_timeout: 30
    oslo_messaging_notifications:
      driver: noop
manifests:
  ingress: false
  service_ingress: false
