annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/changes: |2
        - kind: changed
          description: "Add issuer and extra-list templates that were missing (#825)"
          links:
            - name: "Commit 219ab17"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/219ab17"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: RabbitMQ
      url: https://www.rabbitmq.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq-cluster-operator
    - name: RabbitMQ Cluster Operator
      url: https://github.com/rabbitmq/cluster-operator
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  license: Apache-2.0
apiVersion: v2
appVersion: 2.19.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/cloudpirates
  version: 2.x.x
description: Kubernetes operator to deploy and manage RabbitMQ clusters.
home: https://www.rabbitmq.com
icon: https://a.storyblok.com/f/143071/512x512/aa1bd68288/rabbitmq-logo.svg
keywords:
- rabbitmq-cluster-operator
- rabbitmq
- operator
- message broker
- amqp
- messaging
- queue
maintainers:
- email: hello@cloudpirates.io
  name: CloudPirates GmbH & Co. KG
  url: https://www.cloudpirates.io
- name: Gasper Oblak
  url: https://about.bl4ko.com
name: rabbitmq-cluster-operator
sources:
- https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq-cluster-operator
- https://github.com/rabbitmq/cluster-operator
type: application
version: 0.1.5
