keycloak_host: kc.daalu.io
kube_prometheus_stack_alertmanager_host: alertmanager.daalu.io
kube_prometheus_stack_grafana_host: grafana.daalu.io
kube_prometheus_stack_prometheus_host: prometheus.daalu.io
openstack_helm_endpoints_barbican_api_host: key-manager.daalu.io
openstack_helm_endpoints_cinder_api_host: volume.daalu.io
openstack_helm_endpoints_designate_api_host: dns.daalu.io
openstack_helm_endpoints_glance_api_host: image.daalu.io
openstack_helm_endpoints_heat_api_host: orchestration.daalu.io
openstack_helm_endpoints_heat_cfn_api_host: cloudformation.daalu.io
openstack_helm_endpoints_horizon_api_host: dashboard.daalu.io
openstack_helm_endpoints_ironic_api_host: baremetal.daalu.io
openstack_helm_endpoints_keystone_api_host: identity.daalu.io
openstack_helm_endpoints_magnum_api_host: container-infra.daalu.io
openstack_helm_endpoints_magnum_registry_host: container-infra-registry.daalu.io
openstack_helm_endpoints_manila_api_host: share.daalu.io
openstack_helm_endpoints_neutron_api_host: network.daalu.io
openstack_helm_endpoints_nova_api_host: compute.daalu.io
openstack_helm_endpoints_nova_novnc_host: vnc.daalu.io
openstack_helm_endpoints_octavia_api_host: load-balancer.daalu.io
openstack_helm_endpoints_placement_api_host: placement.daalu.io
openstack_helm_endpoints_region_name: RegionOne
openstack_helm_endpoints_rgw_host: object-store.daalu.io
