---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.kez-ironcloud.duckdns.org"

- name: Add hostname entry to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}.kez-ironcloud.duckdns.org {{ inventory_hostname }}"
    state: present

- name: Create systemd resolved config directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Configure systemd resolved search domain
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/99-search.conf
    content: |
      [Resolve]
      Domains=kez-ironcloud.duckdns.org
    mode: '0644'

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  ignore_errors: true

- name: Restart systemd-hostnamed
  ansible.builtin.systemd:
    name: systemd-hostnamed
    state: restarted

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
