{{- if and .Values.msgTopologyOperator.enabled .Values.msgTopologyOperator.metrics.serviceMonitor.enabled .Values.msgTopologyOperator.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "rmqco.msgTopologyOperator.fullname" . }}
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
    {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.additionalLabels }}
    {{- include "cloudpirates.tplvalues.render" (dict "value" .Values.msgTopologyOperator.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  namespace: {{ default (include "cloudpirates.namespace" .) .Values.msgTopologyOperator.metrics.serviceMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.msgTopologyOperator.metrics.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: messaging-topology-operator
      # We need an extra label for the ServiceMonitor to scrape it correctly
      type: metrics
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.selector }}
      {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.msgTopologyOperator.metrics.serviceMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "cloudpirates.namespace" . }}
  endpoints:
    - port: http
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.interval }}
      interval: {{ .Values.msgTopologyOperator.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.msgTopologyOperator.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.msgTopologyOperator.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.msgTopologyOperator.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.msgTopologyOperator.metrics.serviceMonitor.relabelings }}
      relabelings: {{ toYaml .Values.msgTopologyOperator.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
