images:
  tags:
    staffeln_api: ghcr.io/vexxhost/staffeln:v2.2.3
    staffeln_conductor: ghcr.io/vexxhost/staffeln:v2.2.3
    staffeln_db_sync: ghcr.io/vexxhost/staffeln:v2.2.3
    db_init: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    db_drop: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
    bootstrap: docker.io/openstackhelm/heat:2024.1-ubuntu_jammy
pod:
  replicas:
    api: 1
    conductor: 1
conf:
  staffeln:
    conductor:
      backup_metadata_key: "__staffeln_backup"
      retention_metadata_key: "__staffeln_retention"
    database:
      connection_recycle_time: 600
      max_overflow: 50
      max_pool_size: 5
      pool_timeout: 30
manifests:
  ingress_api: false
  service_ingress_api: false
