# values.yaml for jetstack/cert-manager

installCRDs: true
nodeSelector:
  kubernetes.io/os: linux
  openstack-control-plane: enabled

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# Optional: if you want to override images like the ansible vars did, you can:
# image:
#   repository: quay.io/jetstack/cert-manager-controller
#   tag: v1.14.5
#
# webhook:
#   image:
#     repository: quay.io/jetstack/cert-manager-webhook
#     tag: v1.14.5
#
# cainjector:
#   image:
#     repository: quay.io/jetstack/cert-manager-cainjector
#     tag: v1.14.5
#
# startupapicheck:
#   image:
#     repository: quay.io/jetstack/cert-manager-startupapicheck
#     tag: v1.14.5
