{{- if .Values.clusterOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
  name: {{ template "rmqco.clusterOperator.fullname" . }}
  namespace: {{ include "cloudpirates.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "rmqco.clusterOperator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "rmqco.clusterOperator.serviceAccountName" . }}
    namespace: {{ include "cloudpirates.namespace" . }}
{{- end }}
