# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: daalu-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.110-192.168.0.115

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: daalu-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - daalu-pool