modules:
  default:
    collectors: ["bmc", "ipmi", "chassis", "sel"]
    exclude_sensor_ids:
      - 42
      - 45
      - 48
      - 49
      - 50
      - 51
      - 52
      - 54
      - 57
      - 59
      - 82
      - 88
      - 89
      - 90
      - 109
      - 111
      - 164
      - 167
      - 168
      - 178
      - 180
      - 182
      - 185
