# SPDX-License-Identifier: Apache-2.0

minio_helm_release_name: minio
minio_helm_chart_path: "../../../charts/minio/"
minio_helm_chart_ref: /usr/local/src/minio
minio_helm_release_namespace: object-storage
minio_helm_kubeconfig: "{{ kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
minio_helm_values: {}

_minio_helm_values:
  mode: standalone
  rootUser: admin
  rootPassword: admin1010
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: ClusterIP
